### ISSUE TITLE
Generation of intermediate TagUI script by TagUI-Python - NA for Python

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#10]
@kensoh, In TagUI, you generate an intermediate .js script.

Out of curiosity, for TagUI-Python, do you generate an intermediate TagUI script that we can modify and run directly using TagUI?

**Comment by kensoh** [comment]
Hi CK, if debug mode is set to True with `t.debug(True)`, there will be tagui_python.log file which shows the steps in TagUI that were run. That log of the steps can be saved as a TagUI script to run. 

But it is not 100% directly useable because other actions can be done in Python which are not logged there (only actions requiring TagUI execution engine is logged there).

Also, during execution, there is actually a tagui_python.js script. But it is not useful, only a simple TagUI script with live step to kick-off accepting instructions from TagUI for Python.

**Comment by kensoh** [comment]
Closing this issue for now to focus on other open issues but do add on if anything!
