### ISSUE TITLE
[TAGUI][ERROR] - TagUI process ended unexpectedly - pending replication

### ISSUE THREAD

**Issue by convexset** [tebelorg/TagUI-Python#20]
I see "TagUI process ended unexpectedly" this message from time to time, accompanied by a stream of errors telling me to use `init()` before other things? Is it possible to have things fail more loudly?

**Comment by kensoh** [comment]
Hi @convexset can you try running in debug mode with `t.debug(True)`? It will show the communication between TagUI for Python and TagUI, and also retain the tagui_python.log of this communication log after the execution.

If you have some way to replicate the issue, let me know too. Eg after running a specific action, or after a certain period of time etc etc. Also, try upgrading to the latest v1.6 to see if the issue continues to happen. In that version, I explicitly kill off all TagUI-related processes in init() to make sure everything starts fresh. (for eg if user forget to close() or Ctrl+C to break the execution prematurely, there can be dead processes still in memory).

Hopefully there will be clues so that I can look deeper. The problem is likely the communication channel from this Python package to TagUI instead of something broken with TagUI (because it has been used to run automation lasting more than 10 hours without issue). Thanks for raising this!

**Comment by kensoh** [comment]
Adding on, it looks like the only way the error message happens is when the subprocess TagUI process ends prematurely. With the debug log and possibly replication steps, hope to find out what is amiss.

**Comment by convexset** [comment]
I ended up just coding around the problem. It still occurs sporadically, but the process just restarts.

**Comment by convexset** [comment]
Next time, if there's something I see as reproducible, I'll go that way first.

**Comment by kensoh** [comment]
Thanks for the update. In the meantime, if you can, are you able to run the original code to trigger the issue? If not, I'll watch out the next time you have more inputs on this.

Run with **```debug(True)```** so that you can pass me the **tagui_python.log** (instructions sent to TagUI and stdout) file when the sporadic issue happens. Also, in the tagui installation folder, there is **src/tagui_chrome.log** (direct socket communications with Chrome browser) and **src/tagui.sikuli/*logs** (communication log with SikuliX) which can be helpful in tracing the cause of the process terminating. For Windows, the folder is in ***%APPDATA%\tagui*** for macOS / Linux that folder is in ***~/.tagui*** folder.
