### ISSUE TITLE
Facing issues while downloading TagUI installation - pending replication

### ISSUE THREAD

**Issue by ruturajdev** [tebelorg/TagUI-Python#22]
Dear Ken Soh,

From 1st July I am facing issue with the python script. Whenever I'm running the python script it starts downloading the update file, but fails after some time which leads to error in the execution.
Even I downloaded the file from the link and placed it in the desired folder but even though the issue is not solved. I am getting the following error.

![error](https://user-images.githubusercontent.com/49855122/60529675-bac6ac80-9d14-11e9-87d5-cfda3316f5a4.PNG)

**Comment by kensoh** [comment]
Hi @ruturajdev thanks for raising this issue. Can you try upgrade to the latest TagUI for Python version with `pip install tagui --upgrade` and see if you get the same error again?

Also, can you tell me more about how you are using the script? TagUI for Python will only download the TagUI installation once during the first run. After that, it only syncs the required delta files. So above behaviour to download every run is not expected.

I use GitHub repository to host the installation files, from above error it might be a network related issue - maybe firewall, or anti-virus scanner, or for some reason GitHub server is blocking connections from the location you are running the script. You can also try to see if you can replicate the problem on your colleague's laptop, so that we can isolate the cause of the problem and fix it.

**Comment by ruturajdev** [comment]
Hi, @kensoh I was able to download the file.  As you said I had a network related issue that's the reason I was unable to download.

**Comment by kensoh** [comment]
Hi @ruturajdev thanks for your update, I see.. Sure let me know if you run into any unusual issue again! After the first-time download, subsequent runs should not download again.

And when you do `pip install tagui --upgrade`, it will only sync the small delta core files for new version and not download everything again.
