### ISSUE TITLE
Running time doubled when in function - functions were called twice

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#26]
@kensoh, while testing python functions, modules, classes, etc. as highlighted in Issue #25, there's one strange behaviour I noticed.

For the 2 scripts below that achieves the same thing:
Sample Code 1 - takes 15.86 seconds
Sample Code 2 - takes 36.92 seconds (almost doubled!)

Can you think of any reasons why this is so?
 
### Sample Code 1 - A simple script in sequential order

~~~python
from pandas import DataFrame
import tagui as t
t.init()

t.url('https://www.goodreads.com/list/show/17347.Books_that_ll_help_you_deliver_stunning_presentations')

list_title = t.read('//h1[contains(@class, "h1")]')
print("list_title = " + list_title)

num_books = t.count('//td/a//span[@itemprop="name"]')
print("num_books = ", num_books)

books = [''] * num_books
url = [''] * num_books
sno = [''] * num_books
for n in range(1, num_books+1):
	sno[n-1] = n

	books[n-1] = t.read(f'(//td/a//span[@itemprop="name"])[{n}]/..')
	print(n, "book = "+books[n-1])

	url[n-1] = t.read(f'(//td/a/@href)[{n}]')
	print("   url = "+url[n-1])

Books_Info = {'Sno':sno, 'Title': books, 'URL': url}
df = DataFrame(Books_Info, columns=['Sno','Title', 'URL'])
export_csv = df.to_csv ('book_list1.csv', index = None)
~~~

### Sample Code 2 - using functions

~~~python
from pandas import DataFrame
import tagui as t
t.init()

def read_list_title():
	list_title = t.read('//h1[contains(@class, "h1")]')
	print("list_title = " + list_title)

def read_element(selector):
	t.hover(selector)
	val = t.read(selector)
	return val

def read_book_list():
	num_books = t.count('//td/a//span[@itemprop="name"]')
	print("num_books = ", num_books)
	sno = [''] * num_books
	books = [''] * num_books
	url = [''] * num_books

	for n in range(1, num_books+1):
		sno[n-1] = n

		books[n-1] = read_element(f'(//td/a//span[@itemprop="name"])[{n}]/..')
		print(n, "book = "+books[n-1])

		url[n-1] = read_element('(//td/a/@href)[{}]'.format(n))
		print("   url = "+url[n-1])

	Books_Info = {'Sno':sno, 
		'Title': books, 
		'URL': url
	}
	save_to_csv(Books_Info, 'book_list2.csv')

def save_to_csv(data, csv_file):
	df = DataFrame(data, columns=['Sno','Title', 'URL'])
	export_csv = df.to_csv (csv_file, index = None)

# main program starts here
t.url('https://www.goodreads.com/list/show/17347.Books_that_ll_help_you_deliver_stunning_presentations')
read_list_title()
read_book_list()
~~~

**Comment by ck81** [comment]
@kensoh, for your info, have also tested Sample Codes 3, 4 and 5 in Issue #25,
Sample Code 2 - takes 15.86 seconds
Sample Code 3 - takes 36.92 seconds
Sample Code 4 - takes 36.87 seconds
Sample Code 5 - takes 37.12 seconds

**Comment by kensoh** [comment]
Hi CK, yes this behaviour is not expected. Running the same code as Python functions should not double the execution time. My best guess is you can look at below function that you defined.

```py
def read_element(selector):
	t.hover(selector)
	val = t.read(selector)
	return val
```

In the original code without functions, each read is done in 1 step with t.read(). However, in your code with functions, the above function you defined is used instead when performing reads. This actually becomes 2 steps, first to simulate a hover of mouse over an element, and then reading it.

You can change it to below and try to see if the execution time becomes normal again -

```py
def read_element(selector):
	#t.hover(selector)
	#val = t.read(selector)
	return t.read(selector)
```

**Comment by ycx91** [comment]
Hi CK, creating functions have their own overheads in python and are likely the biggest culprits in terms of increasing time taken.
Could you share your time testing methodology/script? 
If it includes the code of creating the functions themselves, then the time is definitely going to increase by a lot.

**Comment by ck81** [comment]
Hi Ken, yes, you're right!

The doubled time is because of that additional `t.hover`!

When I commented that line out, both timing is the same.  Thanks a lot!

**Comment by kensoh** [comment]
Thanks @ycx91 for sharing your thoughts and CK for your update!

Yes wrapping code within functions will in incur overheads. But I'll think the overheads will be negligible because Python is already a matured optimised programming language and more importantly for UI automation scripts, the main overhead is usually the lag time for the target webapp or application to load / react / respond. So infrastructural overheads should be small compared to the actual run time.

When I saw that the execution time is doubled, something must be amiss somewhere. And saw the function where each read action has 2 actions on the UI, so that's the first thing to dig more.

**Comment by ycx91** [comment]
@kensoh:
Consider the below code:
```
'''
##power2calc Module##
#nothing here

##power2func Module##
def calc():
    return 100**100
'''

import timeit
print (timeit.timeit(stmt='100**100', setup="import power2calc as p1", number=1000000))
print (timeit.timeit(stmt='p2.calc()', setup="import power2func as p2", number=1000000))
```
Results:  
0.8660535310000057
1.0162363419999991

I would think considering the overhead of 1 function to be about 10% increase, that given an increase in complexity and number of functions used, the overheads will add up over time.

**Comment by kensoh** [comment]
This is cool stuff, thanks @ycx91 for sharing! Wow, for above is 17% overhead for functional implementation. I guess if for functions with many statements this overhead will become lesser fraction of the total execution time, because it is fixed cost.

For above function with 1 line, the effort to declare and call a function would have a significant cost relative to the 1 line statement. Above is cool trick to test and optimise performance, thanks!

**Comment by kensoh** [comment]
I tried similar test with a 10-line function. For 1-line function the overhead is 24%.

For 10-line function, overhead is 6%, which is still surprisingly costly to me.

Maybe using [PyPy](https://pypy.org) running compiled code this can be brought down.

**Comment by ck81** [comment]
> For 10-line function, overhead is 6%, which is still surprisingly costly to me.

@kensoh, I'm not that worried about the overhead or speed.  In RPA, speed is not the real concern.  I remembered you told me earlier that in TagUI, you actually purposely make the robot run slower - so as to simulate more closely to the speed of a human being.  Also, for most of the websites, the loading and refreshing of webpage takes some time (it's actually super-slow in my company).  RPA won't work when it runs too fast.

To me, the ability to consolidate groups of functions into modules or classes outweighs the speed or overhead.  In a recent TagUI project that I've written for my company, there are more than 50 tagui files scattered across 6 different folders! It is very challenging trying to re-use and maintain these 50+ scripts.

**Comment by kensoh** [comment]
Thanks CK, what you said is 💯 true 👍 

Just that for this project, performance and overheads are important factors. Because the goal is to eventually inspire developers in other programming languages to port this project architecture and code to their language. So bad design, if any, should be addressed now before it gets cloned to other new projects (eg TagUI for NodeJS, TagUI for Go, TagUI for Java etc etc).

Also, as this project is an additional layer on top of TagUI, minimising overheads where practically possible is preferred, in order to achieve comparable performance as usual TagUI workflows.
