### ISSUE TITLE
Minor suggestion - auto-wait & timeout for UI element [already implemented]

### ISSUE THREAD

**Issue by convexset** [tebelorg/TagUI-Python#4]
This is pretty sweet stuff but I think a little more sugar can't hurt. I have found the following to be useful because such automations can be quite brittle:
```
def t_wait_for(item, dt = 0.1):
	while not t.present(item):
		t.wait(0.1)
```
Then again, it strikes me that many of the actions could benefit from having a `wait` keyword argument to indicate whether to have this done before the relevant action.

Furthermore, time outs can be included as yet another keyword argument. (There already is an implicit time out of 0, why not customise it?)

What do you think?

**Comment by kensoh** [comment]
This is a great suggestion, thanks Jeremy! This auto-wait behaviour is already part of existing design. Given the brittleness of UI automation, it should be part of any good UI automation framework.

The default timeout is 10 seconds and can be changed using t.timeout(). I cover that only briefly in the readme below (timeout() function) to keep documentation simple while covering key features -

https://github.com/tebelorg/TagUI-Python#pro-functions

The implementation is done by injecting a custom JS function exist() directly to the underlying TagUI framework, which is then called using the exist() function in TagUI for Python, used within each UI interaction function.

This minimises I/O messages between TagUI for Python and TagUI, as the loop is done in TagUI. That helps to optimise performance / CPU usage. More importantly, it keeps the debug log and output clean when t.debug(True) is used.

**Comment by kensoh** [comment]
The automatic waiting and timeout() setting deserves to be more visible then just within the pro functions section. Updated readme to add a short paragraph at start of API reference.

https://github.com/tebelorg/TagUI-Python#api-reference

**Examples of using timeout() and exist() to wait for some element**
```python
t.timeout(300)
if exist(element_identifier):
    t.click(element_identifier)
    t.xxx()
    t.yyy()
    t.zzz()
```

```python
t.timeout(300)
if not exist(element_identifier):
    t.echo('some message before quitting')
    sys.exit()

# rest of actions to do
```

```python
t.timeout(99999)
exist(element_identifier)
# rest of actions to do
```

```python
t.timeout(300)
t.click(element_identifier)
```

**Comment by kensoh** [comment]
Upstream TagUI folder has a bug when timeout is changed, for visual automation, it can revert back to default of 10 seconds. The bug has been fixed in PR https://github.com/kelaberetiv/TagUI/pull/453. 

This is in new installations or upgrades. For existing installations, running `t.setup()` would pull in the fix so that visual automation using images would follow the timeout specified by `t.timeout()`.

**Comment by kensoh** [comment]
Upstream TagUI project has a bug when timeout is changed, for visual automation using images, it can revert back to default of 10 seconds. The bug has been fixed in PR https://github.com/kelaberetiv/TagUI/pull/453. 

This is in new installations or upgrades. For existing installations, running `t.setup()` would pull in the fix so that visual automation using images would follow the timeout specified by `t.timeout()`.
