### ISSUE TITLE
visible() helper function not in TagUI for Python - streamline by design

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#43]
Hi Ken,

Just found out that `visible()` is not present in TagUI-Python!

Is there any particular reason why this is not ported over from TagUI to TagUI-Python?

I'm using `present()` in the meantime, though it could happen that an element is present but not visible.  So being able to test if an element is visible is quite useful sometimes.

**Comment by kensoh** [comment]
Hi CK! This is by design, firstly to streamline the API as most users do not care about the nuance between a visible web element and a present web element and will be confused if there are visible() and present(). Secondly, for visual automation mode, there is no distinction between something being visible() and present(), thus having 2 functions to do the same thing will be confusing.

More details here on removing visible() in favour of keeping only present() - https://github.com/tebelorg/TagUI-Python/issues/12

As a workaround, you can implement your own visible() by copying the function present() in tagui.py and make the following changes -

1. change function name and error message to visible
```py
def present(element_identifier = None):
    if not _started():
        print('[TAGUI][ERROR] - use init() before using present()')
        return False
```
⬇️ 
```py
def visible(element_identifier = None):
    if not _started():
        print('[TAGUI][ERROR] - use init() before using visible()')
        return False
```

2. change the commands sent to TagUI live mode

```py
    send('present_result = present(\'' + _sdq(element_identifier) + '\').toString()')
    send('dump present_result to tagui_python.txt')
```
⬇️ 
```py
    send('present_result = visible(\'' + _sdq(element_identifier) + '\').toString()')
    send('dump visible_result to tagui_python.txt')
```

Alternatively, you can use send() to send the custom TagUI command to run visible(), dump the result, and use _tagui_output() to read the result. I won't recommend send() approach as it unnecessarily complicates your script.

**Comment by ck81** [comment]
> As a workaround, you can implement your own visible() by copying the function present() in tagui.py and make the following changes 

Thanks for the tips, Ken! 

One thing I like about your TagUI and TagUI-Python is how you've added ways for people to extend the functionalities e.g. through `tagui_local.js` in TagUI and `tagui.py` in TagUI-Python.

**Comment by ck81** [comment]
Hi Ken,

Just tried your solution to add `visible()` in tagui.py. It worked perfectly! Thanks!

**Comment by ck81** [comment]
Note: for those who are not sure where to find the file `tagui.py` (which is in the python package folder), you can create a simple python script containing the following 2 lines:

```python
import tagui as t
print(t.__file__)
```

Run the above script and you will see the path of the package folder.

On my windows 10 machine, it's: 
> C:\Users\username\AppData\Local\Programs\Python\Python37-32\Lib\site-packages

On the mac, it's:
> /usr/local/lib/python3.7/site-packages
