### ISSUE TITLE
Visual automation attach to application window on Windows

### ISSUE THREAD

**Issue by tantk** [tebelorg/TagUI-Python#48]
Hi all,
i am using visual automation from tagui to scrap data from an mobile app via bluestack

currently, my solution is to use multiple windows VM on my computer.
each running an instance of tagui and bluestack.

does anyone know if it is possible to let a tagui instance to only focus on the screen of a certain bluestack instance via process id?

**Comment by kensoh** [comment]
Hi @tantk that's an interesting use scenario. TagUI for Python does not directly have access to the process ID or thread of the applications running on Windows. If you are to do it manually, how do you bring to foreground the BlueStacks instance that you want to act on?

Is it possible to use keyboard combinations, eg Alt+Tab with `t.keyboard('[alt][tab]')`, or some unique visual characteristics (eg titlebar text) that can be clicked on (`t.click()`), or some command that can be run from command prompt (`t.run()`) to bring to foreground the window?

**Comment by kensoh** [comment]
PS - for your Windows VM, are you using below solution (VirtualBox + free limited Windows image)? If not, can you share your method that can use Windows images?

https://towardsdatascience.com/how-to-install-a-free-windows-virtual-machine-on-your-mac-bf7cbc05888e

It'll be good for me to have a Windows running on my macOS so that it is easier to test code changes. Right now I borrow a physical Windows laptop whenever I need to test new code.

**Comment by kensoh** [comment]
Closing issue for the time being until further inputs!
