### ISSUE TITLE
How to get current date and write it into calendar section of a web page

### ISSUE THREAD

**Issue by ruturajdev** [tebelorg/TagUI-Python#5]
Hello Ken Soh,
I am working on a TAGUI project where whenever the script for web automation runs the current date should be automatically written in the calendar on the webpage. I am attaching a picture of the calendar followed by this post. Please suggest to me how to automate the calendar.

![calendar](https://user-images.githubusercontent.com/49855122/59681420-8241b180-91f1-11e9-8105-5b2b71534580.PNG)

**Comment by kensoh** [comment]
Hi @ruturajdev this will not be easy but you can try the following by breaking the problem into 2.

1. First is get current date in Python, from below you will see how to get day, month, year.
https://www.saltycrane.com/blog/2008/06/how-to-get-current-date-and-time-in/

2. Second is inspecting the calendar popup on the dates to see if there is any pattern so that you can use XPath to click on the correct date. You also need to convert the month to the string format so that you can choose the month. If the month and year is a dropdown, consider using t.select(element_identifier, option_value), where option_value is the value of the dropdown item.

If all else fails, consider using the visual automation mode where you create images of the days so that you can visually click on them eg t.click('11.png'). Or explore the backend of the webpage so that you can use t.dom() to change the date directly without having to go through calendar popup.

**Comment by kensoh** [comment]
Closing issue for now, but please message here if anything!
