### ISSUE TITLE
SAP R3 automation - web-based yes, desktop based only visual automation

### ISSUE THREAD

**Issue by alakaiobito** [tebelorg/TagUI-Python#67]
Hello Ken,

Is it possible to automate SAP R3 screens using TagUI?

Kind regards,
Alakai

**Comment by kensoh** [comment]
Hi @alakaiobito SAP R3 is a web-based application so it should be possible. But you'll need to google to learn about XPath locators in order to effectively tell TagUI which web element are you trying to interact with. You can also use the computer vision method by providing images.

For desktop applications, only computer vision method by providing images or x,y coordinates, because TagUI has no backend access to the applications program architecture. Mostly only the commercial RPA tools can do that, and only for Windows OS.
