### ISSUE TITLE
Visual automation on Remote Desktop server - pending checks and logs

### ISSUE THREAD

**Issue by onenessboy** [tebelorg/TagUI-Python#70]
Hi,

Here what I observed:

* Locally using windows 10 -->using 100 % magnification -- my script working fine as intended
* RDP to Remote server via RDP --> to a machine with Windows Server 2019 (I have 100 % magnification at local machine , so that when RDP it the target VM also use same magnification)
* setup all python tagui there, ran same program with visual automation, its not moving cursor to inteded places..clicking at wrong places...

Locally same program works fine.  

so is there any limitation of tagui python with version of windows ? or on RDP it wont work properly

please suggest..

**Comment by kensoh** [comment]
I assume you are referring to this Python package and not the original TagUI project that uses human language syntax.

From your description, the most likely issue is because the desktop environment for your server is different from your laptop. Maybe the screen resolution and density is different, so the icons and UI elements at 100% may look different.

You can try developing a simple automation script directly on your remote desktop server and see if that works. If it does not work, check the visual automation engine logs. For windows, It is in the following folder -

%APPDATA%\tagui\src\tagui.sikuli (%APPDATA% is usually C:\Users\Username\Appdata\Roaming)

**Comment by kensoh** [comment]
Closing issue for now until further inputs, do try the suggestions and let me know!
