### ISSUE TITLE
init() error - local PHP being run, pending checks and replication details

### ISSUE THREAD

**Issue by CL545740896** [tebelorg/TagUI-Python#87]
Fatal error: Directive 'allow_call_time_pass_reference' is no longer available in PHP in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'E:/AppServ\php5\ext\php_curl.dll' - �Ҳ���ָ���ĳ���

**Comment by CL545740896** [comment]
WIN7  64bit  Python3

**Comment by kensoh** [comment]
Hi Eric, thanks for raising this!

Is it you get above error after doing `pip install tagui` --> `import tagui as t` --> `t.init()`?

If yes, from above error message it looks like the PHP setup on your computer has a conflict with TagUI's PHP code, because it gets used instead of the PHP that TagUI is packaged with.

The fastest way to solve this should be adding TagUI's PHP path in front of your %PATH% variable, so that the PHP packaged with TagUI is used instead of your local copy above.

The TagUI's PHP folder path is in `%APP_DATA%\tagui\src\php`, can you try adding that in front of your path so that it gets called instead of your local PHP? %APPDATA% is usually the folder C:\Users\Username\Appdata\Roaming

Alternatively, if you are not using PHP on your computer, you can consider uninstalling the PHP at E:/AppServ\php5 directory and it should resolve the issue. Let me know how it goes.

**Comment by kensoh** [comment]
Adding on, I haven't heard of this issue before and not sure why it happens, because TagUI by default will use the PHP executable that is packaged with it instead of a user local copy.

**C:\Users\Username\Appdata\Roaming\tagui\src\tagui.cmd**
```
if exist "%~dp0php\php.exe" set "path=%~dp0php;%path%"
```

Other things that can be tried is how are you running the package? Is it from a normal Windows command prompt, Anaconda command prompt, or PowerShell / Linux shells?

I've heard that the package does not run correctly in PowerShell and Linux shells on Windows, but ok in the normal command prompt / Anaconda command prompt.

**Comment by CL545740896** [comment]
Work well as u say

**Comment by kensoh** [comment]
Thanks Eric! I assume you change from PowerShell / Linux shell to Windows / Anaconda command prompt and it works. I'll look out for other users who have similar problems and update to readme.
