### ISSUE TITLE
Google example doesn't work - should be webpage rendered differently

### ISSUE THREAD

**Issue by CL545740896** [tebelorg/TagUI-Python#88]
![image](https://user-images.githubusercontent.com/27679586/69971882-8b35fd80-155b-11ea-9d9a-788c19e2971e.png)

**Comment by kensoh** [comment]
Hi Eric, from your log above, it looks like your Google webpage when visit from your location is different from mine, when I visit from my country. Can you try following code to see if it works? I'm assuming that your search bar has a name attribute call q.

Below explicitly specifies the XPath of the search bar with name attribute as q -

```py
t.init()
t.url('https://www.google.com')
t.type('//*[@name="q"]', 'decentralization[enter]')
t.snap('page', 'results.png')
print(t.read('resultStats'))
t.close()
```

**Comment by CL545740896** [comment]
It's so good ! but  i found init cost many time to wait,how can i faster to open

**Comment by kensoh** [comment]
Thank you! How long does init() takes for you? The first time it run will take few minutes to download the TagUI files from GitHub, dependent on internet speed and GitHub download speed.

After that it should take few seconds to init() to open the Chrome browser. If you run with visual automation True, it can take 5-15 seconds depending on your laptop speed, because need time to load the computer vision engine (OpenCV and Tesseract ) into memory.

**Comment by kensoh** [comment]
Also, updated readme for google example to use XPath, because the webpage can be rendered differently for different user location. Using XPath should work better for everyone. Thanks!

**Comment by CL545740896** [comment]
> Thank you! How long does init() takes for you? The first time it run will take few minutes to download the TagUI files from GitHub, dependent on internet speed and GitHub download speed.
> 
> After that it should take few seconds to init() to open the Chrome browser. If you run with visual automation True, it can take 5-15 seconds depending on your laptop speed, because need time to load the computer vision engine (OpenCV and Tesseract ) into memory.

Yes, It will cost 5-15 seconds when i use vision , This is so good, If the tagui service can satrt onece then can reuse when i run py  script will be more better to use

**Comment by kensoh** [comment]
Oh I see.. That's correct, it is by design. The upstream TagUI project prioritise stability and accuracy over speed. So its design is to launch the computer engine process each time it is run. This makes sure all programs and processes in memory are fresh and not having garbage from previous runs.

You can try combining your different scripts into 1 script and run, so that you only do `import tagui as t` and `t.init(True)` one time, then do `t.close()` one time after everything you want to run is completed. For Python 3 you can either define functions or use `exec(open('filename').read())` to run other sub-scripts from the parent script. For Python 2, can use execfile() or define functions.
