### ISSUE TITLE
LIVE mode in TagUI-Python for 2FA - live mode NA in Python, use ask()

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#9]
@kensoh, in the documentation it says that:
> TagUI-Python uses TagUI in LIVE mode to send instructions from Python to it

Does this mean that there is now no more LIVE mode in TagUI-Python?  

In TagUI, the LIVE mode is one of the best features that makes TagUI outshine many other RPA tools, even some of the leading ones.  Not only does it allow you to do interactive/live testing and debugging, it also makes it possible to automate those websites that require 2FA (e.g. all the banks in Singapore and also many corporate websites).  

I use the LIVE mode to pause the script so that people can enter username/password followed by 2FA before continuing. 

How to achieve this in TagUI-Python (i.e. pausing the script so that people can perform 2FA)?

**Comment by kensoh** [comment]
Hi CK, correct, there is no live step in TagUI for Python because it is not applicable.

There is already live debugging by default in Python environment - when you type python to enter the interactive shell, or when users use Jupyter notebook to do their development. Whenever a command is entered, there is live feedback to see the output returned and the action taken.

If a Python script is run instead of being in typed out in Python dev environment, you can use t.ask() to prompt user to enter the 2FA, before pressing enter to continue.

```py
t.ask('Please key in your 2FA code and press enter to continue...')
```

**Comment by kensoh** [comment]
Closing this issue for now to focus on other open issues but do add on if anything!
