### ISSUE TITLE
following happens when starting TagUI..

### ISSUE THREAD

**Issue by adegard** [tebelorg/TagUI-Python#96]
Dears,
![image](https://user-images.githubusercontent.com/23522577/71769829-13763c80-2f26-11ea-9a87-73e4274c4247.png)
Installing for first time tagui in Python, give me an error

**Comment by kensoh** [comment]
Hi Arnaud @adegard thanks for trying out TagUI for Python and raising the issue!

The first time t.init() is run the package will try to download TagUI for the OS and set it up for use, and automatically clear some setup issues if possible. During the setup there will be some message saying downloading TagUI.

Above somehow doesn't have that message. Can you tell me how you run the script to replicate the error, or what you do to make it work? So that I can improve the tool and prevent such issue in future. Thanks!

This project is built on the TagUI project. While TagUI is maintained by AI Singapore, I'm maintaining this tool with focus on decentralised usage and deployment without internet. This tool has the same set of UI automation actions but does not have the 21 human languages, and features such as repository, datatable, auditing etc of TagUI.

If you use Python in your projects, you'll enjoy using this tool as part of the other Python packages for your automation requirements. If you find something which can be improved let me know, and I'll see if that can be added.

My vision for this project is a package that does UI automation / RPA very well. But unlike commercial RPA software, this tool is only a component of the many other packages that Python users can combine with to create something sophisticated. It is more like a supporting role and one of the tools in users' toolbox. But commercial RPA software is more like taking the centre stage and the main software for the user in their digital automation work.
